### ISSUE TITLE
Tag Twitter accounts

### ISSUE THREAD

**Issue by 0xdevalias** [openfaas/backer-thankyou#2]
Not sure if the information is exposed via the API's, but it would be cool to @tag the backers twitter account as well.

**Comment by rgee0** [comment]
I think the code does that where the webhook contains the information:

https://github.com/openfaas/backer-thankyou/blob/25007c48d6db35720a02143e2122751e86014b07/patreon-responder/handler.py#L33-L35

**Comment by alexellis** [comment]
Yes they are tagged, but only if they set their Twitter profile ahead of time on Patreon. This seems to be working very well still 👍 I've seen a number of people tagged.
