### ISSUE TITLE
Move secrets to secrets vs env-vars

### ISSUE THREAD

**Issue by alexellis** [openfaas/backer-thankyou#3]
This should be a small change.

Would be good to add a flag so that it can even run on a public OpenFaaS Cloud instance.

**Comment by martindekov** [comment]
Can I take this one ?

**Comment by alexellis** [comment]
I think that would be fine, but when reading secrets check the old location first then the newer location second.

/run/secrets/... /var/openfaas/secrets/

Alex

**Comment by alexellis** [comment]
Derek close: implemented today 👍
